# Generated by Django 5.2.9 on 2025-12-18 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('codigo_dispenser', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_dispenser', models.CharField(max_length=255, unique=True)),
                ('estado', models.BooleanField(default=False)),
                ('permanencia', models.BooleanField(default=False)),
                ('imagenes', models.ManyToManyField(blank=True, related_name='dispensers', to='core.imagen')),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispenser', to='core.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('codigo_solicitud', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='dispenser.dispenser')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='core.ubicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
