# Generated by Copilot on 2025-12-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ubicacion_decimal_unique"),
        ("dispenser", "0002_dispenserimagen_alter_dispenser_imagenes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispenser",
            name="ubicacion",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="dispensers", to="core.ubicacion"),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="fecha_solicitud",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="dispenser",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="solicitudes", to="dispenser.dispenser"),
        ),
        migrations.AddConstraint(
            model_name="solicitud",
            constraint=models.UniqueConstraint(fields=("user", "ubicacion"), name="uniq_solicitud_user_ubicacion"),
        ),
    ]
