# Generated by Django 5.2.9 on 2025-12-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ubicacion_latitud_longitud_float'),
        ('dispenser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenserImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispenser.dispenser')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagen')),
            ],
        ),
        migrations.RemoveField(
            model_name='dispenser',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='dispenser',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='dispensers', through='dispenser.DispenserImagen', to='core.imagen'),
        ),
        migrations.AddConstraint(
            model_name='dispenserimagen',
            constraint=models.UniqueConstraint(fields=('imagen',), name='uniq_dispenserimagen_imagen'),
        ),
    ]
