# Generated by Copilot on 2025-12-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dispenser", "0002_solicitudes_normalizadas"),
    ]

    # Merge no-op: mantiene un único leaf en el grafo.
    operations = []
