# Generated by Copilot on 2025-12-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispenser", "0003_solicitudes_normalizadas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="estado",
            field=models.CharField(
                choices=[("pendiente", "Pendiente"), ("aceptada", "Aceptada")],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="aceptada_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="aceptada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_aceptadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
