# Generated by Django 5.2.9 on 2025-12-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('codigo_imagen', models.BigAutoField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('codigo_ubicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('longitud', models.IntegerField()),
                ('latitud', models.IntegerField()),
            ],
        ),
    ]
