# Generated by Copilot on 2025-12-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_ubicacion_latitud_longitud_float"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ubicacion",
            name="latitud",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="ubicacion",
            name="longitud",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AddConstraint(
            model_name="ubicacion",
            constraint=models.UniqueConstraint(fields=("latitud", "longitud"), name="uniq_ubicacion_lat_lon"),
        ),
    ]
