# Generated by Copilot on 2025-12-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ubicacion_decimal_unique"),
    ]

    # Merge no-op: mantiene un único leaf en el grafo.
    operations = []
